---
title: "HW03: Truncated Normal: Loops & Conditionals"
author: "STAT 370"
output: html_document
---

**We have a server!**  You will put all of your work on this server (starting with this homework, then previous and future assignments, and your project), making everything accessible to the world, (not just the AU community).  You can showcase your work to family, friends, classmates, and future employers.

Point your browser to http://stat370.com/.  This link will bring up a wiki, which you will be able to edit with links to your work on the server.  To edit the wiki, and to put your work on the server, you will need accounts which I will help you set up.  I'll need about one minute for each person, and I will call you up one at a time.  While you are waiting, think of a username and two **strong** and different passwords, follow these steps, and more detailed instructions on the wiki, to put your work online.  You can get started with these instructions before you have accounts.

1. Create a new repository on Github for this homework 3.  For the name, don't use any spaces or special charaters, and it shouldn't be too long.  The repository name will be in the URL for your page.   "hw03" is fine---it is OK if two or more people have the same name for a project---your username will also be in the URL.
2. Create a new project in R-Studio that pulls in your hw03 repository.  After the project exists on your computer, you can just open it.
3. Create a New File, and make it an R-Markdown file.  Choose to make it an html document. That will give you a template.
4. Save the template as "index.Rmd".
5. Knit "index.Rmd" to create the file "index.html".  The webserver will automatically look for the file "index.html".  If you call your file anything other than "index.Rmd", you will also have to put your filename into the URL, which is often not desired.  
6. I am going to suggest that you put R-Studio's _template_ on the server first, (i.e. what you just saved, in place of your homework), just to see if this works, then, later, you will complete the assignment and update the server with your completed assignment.
7. No need to do this yet, but in the step (9) you'll want to stage, commit, and push "index.Rmd" to Github---but don't push the built file "index.html" to Github.  Instead, let the server recreate "index.html" for you---the server has R installed and I'll show you how to make it work.  Just so you know: it is considered bad practice to put built files (like "index.html") in your repository because there can never be any guarantee that such built files are up to date with the rest of your repository.  However, if, for some reason, you remain unable build files on the server, do remember that adding the html files to your repository will in fact work to put them on the web.
8. You will want to put the code for building your page or site into your repository.  Instructions for building a R-Markdown pages (used here) are different from the instructions for R-Markdown websites (used earlier).  Both will be put in file called "Makefile" provided in a Github repository.  See the stat370.com wiki for a link and for more detailed instructions.
9. Once you have the correct Makefile added to your project: stage, commit and push "index.Rmd" and "Makefile" to Github and check that they are there.
10. Follow directions on the stat370.com website to make your template available on the web.  This will involve setting up your account on the wiki, setting up your account on the server (after getting accounts from me), then pulling your project repository from Github onto the server, building the html file, and updating the wiki with a link to your document.  Next to the link to your document, you should also include link to your Github repository and to the assignment (i.e. this html file).
11. Now for the assignment!  I am going to give a lecture on loops and conditionals.  If you are ahead of the class, please put your previous homework, and project progress, if you have any to show, on the server, while you wait for the class to catch up.
12. You know the functions "rnorm()" and "dnorm()".  The first gives a random number with Normal distribution and the second gives the probability density function (whose graph is the density curve) for the Normal distribution (i.e. a perfect bell curve).
13. You are going to write functions "rmytnorm()" and "dmytnorm()" with the same arguments.  These will implement the Normal distribution with the important difference that it will be impossible for the random variable to be a negative number---when a negative number appears, new random numbers are chosen, until a positive one appears.
14. It turns out these functions have already been written as "rtnorm()" and "dtnorm()" and can be found in the package "msm".  You are not going to load this library.  Instead, you are going to create your own versions, for the purposes of learning to use loops and conditionals only.  The libary will undoubtedly have much better code---perhaps they don't even use loops and conditionals.  In the future, if you need a truncated Normal, use the library.  Write these functions as an exerise only.
15. For rmytnorm(10), you will call rnorm(1), enough times to get ten positive numbers, throwing away any that are negative, and trying again until you get a positive one.  For the purposes of this exercise, only call rnorm with the argument $n=1$, but do implement the other arguments.
16. For dmytnorm(x) you will set the result to zero if x is negative, and use dnorm(x) if x is positive---however you must rescale dnorm(x) so that the area under the density curve is 1.  Ask me for help if you need it.  Explain how you solved this problem in the dynamic document---even if I helped you.
17. I want you to try out your functions for a truncated normal whose mode is positive and one whose mode is negative---but don't put the mode more than two standard deviations below zero.  In an untruncated normal, the mode is the same as the mean, which is the argument "mean".
18.  In the dynamic document, for each case (mode negative, mode positive), print out a few random numbers, plot a histogram of the random number (should be many more than you printed out), and plot the density curve.
19.  Remember to update the server with your completed assignment, see instructions on wiki.